### ISSUE TITLE
is_mandatory break the steps and the machines

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#24]
When is_mandatory is used in Input or Menu machines after  the CANCEL_DURATION delay the steps and machines are stopped.

To fix it:
shellbot/machines/input.py +400
-                 if self.elapsed > self.CANCEL_DELAY:
+                if self.elapsed > self.CANCEL_DELAY and not self.is_mandatory:

Thanks

**Comment by bernard357** [comment]
I will try to remove lines 400-401 and report on the outcome

**Comment by bernard357** [comment]
related tests had to be modified as well. will be integrated in next commits, thanks
