### ISSUE TITLE
Issue to upload file when command is used

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#29]
When command is used and file is associated to this post, an issue appear in the command treatment:
```bash
12:14:32 execute() got an unexpected keyword argument 'url'
Traceback (most recent call last):
  File "/var/www/test/shellbot/shellbot/listener.py", line 113, in run
    self.process(item)
  File "/var/www/test/shellbot/shellbot/listener.py", line 187, in process
    self.on_message(event)
  File "/var/www/test/shellbot/shellbot/listener.py", line 287, in on_message
    self.engine.shell.do(input, received=received)
  File "/var/www/test/shellbot/shellbot/shell.py", line 301, in do
    command.execute(bot, **kwargs)
TypeError: execute() got an unexpected keyword argument 'url'
```

Other related tests: 
* No issue when file is uploaded via the Input command
* No issue to copy the file in another room (in my test from direct to group)

but anyway thanks for this useful feature!!!

**Comment by bernard357** [comment]
Thanks Guillain for the feed-back. Are you talking of a command that you develop? If yes, then it should be ready for extra arguments. Wherever this command can handle file uploads or not, you are advised to declare it with ``**kwargs`` in the end.

The recommended approach for new commands is the following:

```
def execute(self, bot, arguments=None, **kwargs):
    ...
```

For commands that can handle file attachments, you could write the following:

```
def execute(self, bot, arguments=None, attachment=None, url=None, **kwargs):
    ...
    if attachment:  # a document has been uploaded with this command
        ....
```

Does this help on your issue?

**Comment by bernard357** [comment]
Examples reflected in 855264fd996bcac2e0bd69de60822736a892df9f

**Comment by guillain** [comment]
As usual Bernard is Amazing :)
Fixed with the Attachments=None .

Thanks !
