### ISSUE TITLE
multi instance ko caused by ZMQ

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#31]
When a second bot is started on the same server ZMQ can't start as a process is already running.
Need to have the capability to set ZMQ as global (possible?) Or define one instance by bot.
Thanks in advance for your help

**Comment by bernard357** [comment]
When the shellbot.bus module is started it checks for the variable settings ``bus.address`` and if none is set, it takes default value. So the trick to run multiple instances of shellbot on the same host is to set a different value for ``bus.address`` in individual configuration files. This should be better documented of course ... Is this enough information for you to proceed?

**Comment by guillain** [comment]
Yep,

Fixed as explained.
Just be careful to the host declaration, localhost is not accepted when 127.0.0.1 works well

can be set as bellow:
```bash
export ZMQ_CONNECT="tcp://127.0.0.1:5555"
```
settings.py
```bash
settings = {     'bus.address': os.environ["ZMQ_CONNECT"], }
```

thanks
