### ISSUE TITLE
First character of command can be lower or upper case

### ISSUE THREAD

**Issue by bernard357** [bernard357/shellbot#34]
Since shellbot is commonly used from diverse devices, it has to adapt to various situations. Feedback from users is that mobile devices puts first character in chat box as upper case, where the same from laptops/desktops puts first character in lower case. Since most commands are in lower case today, it is creating some friction when typing a command in 1:1 space.

The solution is to put the first token submitted to the shell to lower case, so that the right command is ran whatever device is used.

**Comment by guillain** [comment]
Update works well on DE script.
Commands are now understable with upper and lower case, thanks!

**Comment by bernard357** [comment]
Thanks @Guillain for the feedback. The same will be done for names of lists, so keep posted
