### ISSUE TITLE
do not use named lists in direct channels

### ISSUE THREAD

**Issue by bernard357** [bernard357/shellbot#36]
Named lists are a convenient way to add people to a channel. However, direct channels are only aiming to support 1:1 interactions. Therefore, the usage of named lists should be harmless in a direct channel.

**Comment by bernard357** [comment]
@guillain this should help for your bot, since lists should not be activated in 1:1 Cisco Spark rooms anymore. Thanks for your next feedback

**Comment by guillain** [comment]
ToDo and in my backlog ^^

**Comment by guillain** [comment]
Yep,
It's validated ;)
Thanks Bernard!

**Comment by bernard357** [comment]
okay, now closing this issue after this feedback. Thanks Guillain
